export const WRITE_WEATHER = 'WRITE_WEATHER';
export const FETCH_GET_WEATHER = 'FETCH_GET_WEATHER';
export const WRITE_CITY = 'WRITE_CITY';
export const WRITE_UNIT = 'WRITE_UNIT';
export const WRITE_ERROR = 'WRITE_ERROR';
export const TOGGLE_WEATHER_LOADER = 'TOGGLE_WEATHER_LOADER';
export const FETCH_GET_WEATHER_BY_LOCATION = 'FETCH_GET_WEATHER_BY_LOCATION';